#!/usr/bin/env bash

IS_WORKING_VST=$( nm "$1" | grep _VSTPluginMain | wc -l )
# Check to make sure the main entry point to the VST Plugin symbol exists in the binary.
if [[ $IS_WORKING_VST -eq 1 ]]; then
  exit 0
fi
echo "Missing VST symbols! Check your linker flags!"
exit 1