package (
    default_visibility = ["//visibility:public"]
)

exports_files([
  "FileTemplates/AudioUnitResource.txt",
  "FileTemplates/AudioUnitInfoPList.txt",
  "FileTemplates/VSTInfoPList.txt",
])
